# Generated by Django 4.2.17 on 2024-12-29 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=255)),
                ('description', models.TextField(help_text='Description of the task')),
                ('start_date', models.DateField(help_text='Start date of the task')),
                ('end_date', models.DateField(help_text='End date of the task')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('created_by', models.ForeignKey(help_text='The user who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
