# Generated by Django 4.2.17 on 2025-01-10 23:57

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('authentification', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='working_schedule',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='goal_statement',
            field=models.TextField(blank=True, help_text='Describe your goals or motivations.', max_length=1000),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='interest_areas',
            field=models.JSONField(default=dict, help_text="A dictionary with interest areas as keys and their scales (0-3) as values, e.g., {'Environmental Protection': 3, 'Education': 2}."),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='Tags representing areas of interest.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='schedule',
            field=models.JSONField(default=dict, help_text="A dictionary where keys are weekdays and values are lists of available time ranges, e.g., {'Thursday': ['14:00-17:00'], 'Friday': ['10:00-17:00']}."),
        ),
    ]
