# Generated by Django 4.2.17 on 2025-01-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_volunteerprofile_working_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='goal_statement',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='interest_areas',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='field_areas',
            field=models.JSONField(default=dict, help_text="A dictionary mapping interests to their levels (e.g., {'ENVIRONMENT': 2, 'EDUCATION': 3})."),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='schedule',
            field=models.JSONField(default=dict, help_text="A dictionary mapping days to time ranges (e.g., {'Monday': ['14:00-16:00'], 'Friday': ['10:00-12:00', '15:00-17:00']})."),
        ),
    ]
