# Generated by Django 4.2.17 on 2025-01-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_volunteerprofile_goal_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='goal_statement',
            field=models.TextField(blank=True, help_text='Describe your goals or motivations.', max_length=1000),
        ),
    ]
