# Generated by Django 4.2.18 on 2025-01-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_volunteerprofile_goal_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='field_areas',
            new_name='competencies_areas',
        ),
    ]
